pthread.o: pthread.cc \
 /home/ugb/lnberry/cpsc457a2/kos/src/ulib/../testoptions.h \
 /home/ugb/lnberry/cpsc457a2/kos/src/ulib/../include/syscalls.h \
 /home/ugb/lnberry/cpsc457a2/kos/src/ulib/../include/kostypes.h \
 /home/ugb/lnberry/cpsc457a2/kos/src/ulib/../include/pthread.h \
 /home/ugb/lnberry/cpsc457a2/kos/src/ulib/../include/syscalls.h
libKOS.o: libKOS.cc \
 /home/ugb/lnberry/cpsc457a2/kos/src/ulib/../testoptions.h \
 /home/ugb/lnberry/cpsc457a2/kos/src/ulib/../include/syscalls.h \
 /home/ugb/lnberry/cpsc457a2/kos/src/ulib/../include/kostypes.h
